### ISSUE TITLE
arch model 为什么不选择Mirnet-v2

### ISSUE THREAD

**Issue by quhaoooo** [wangchx67/SYSU-FVL-T2#2]
请问大佬，你们比赛为什么不选择Mirnet-v2, 而是Uhd呢？ 是Mirnet有什么缺陷吗

**Comment by wangchx67** [comment]
其实是编解码器和多尺度网络的不同特性  尝试多次试出来的   但是MIRNETV2的多尺度比较吃显存  training size提不上去

**Comment by quhaoooo** [comment]
感谢大佬~
