### ISSUE TITLE
项目是在linux下跑的吗？

### ISSUE THREAD

**Issue by yimuya** [wangchx67/SYSU-FVL-T2#3]

**Comment by wangchx67** [comment]
yes

**Comment by yimuya** [comment]
windows下可不可以

**Comment by wangchx67** [comment]
环境配好是都可以的

**Comment by yimuya** [comment]
我看你用的是cuda11.1的，但是我的电脑是cuda11.3,我就用了跟您不一样的torch环境，但是最终会有RuntimeError: No CUDA GPUs are available的问题 这个您了解吗

**Comment by wangchx67** [comment]
配环境windows 和linux不一样的 所以cuda环境就需要你自己去配适合windows的了

**Comment by yimuya** [comment]
好的 非常感谢
